services:
  - type: web
    name: agrirakshak-model
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"

  - type: web
    name: agrirakshak-backend
    env: python
    region: singapore
    plan: free
    rootDir: agrirakshak/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PREDICTION_API_URL
        value: https://agrirakshak-model.onrender.com
